# Generated by Django 5.2.9 on 2026-10-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0010_add_query_indexes'),
        ('helios_auth', '0002_bridgeloginrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotPolicyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=250)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('retain', 'Retain')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='helios_auth.user')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helios.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helios.voter')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('election', 'voter', 'event_key'), name='helios_policy_event_unique')],
            },
        ),
    ]
