# Generated by Django 5.2.9 on 2026-10-06 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0011_ballotpolicyreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluElectionBinding',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='helios.election')),
            ],
        ),
    ]
