# Generated by Django 5.2.9 on 2026-10-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0012_aluelectionbinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluRateBucket',
            fields=[
                ('key', models.CharField(max_length=85, primary_key=True, serialize=False)),
                ('hits', models.PositiveSmallIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
